///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: sound/completed.aks
/// Generation time: Fri 20 Nov 2020 05:00:12 PM CET
///

/// Song 'g_completed' metadata macros
#define g_completed_address  0x049E
#define g_completed_size     294
#define g_completed_end      0x5c3

/// Song 'g_completed' array declaration
extern void g_completed[g_completed_size];
