///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: sound/end.aks
/// Generation time: Fri 20 Nov 2020 05:00:12 PM CET
///

/// Song 'g_end' metadata macros
#define g_end_address  0x032C
#define g_end_size     370
#define g_end_end      0x49d

/// Song 'g_end' array declaration
extern void g_end[g_end_size];
