///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: sound/fx.aks
/// Generation time: Fri 20 Nov 2020 05:00:12 PM CET
///

/// Song 'g_fx' metadata macros
#define g_fx_address  0x05C4
#define g_fx_size     461
#define g_fx_end      0x790

/// Song 'g_fx' array declaration
extern void g_fx[g_fx_size];
