///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: sound/ingame.aks
/// Generation time: Fri 20 Nov 2020 05:00:11 PM CET
///

/// Song 'g_ingame' metadata macros
#define g_ingame_address  0x0791
#define g_ingame_size     1654
#define g_ingame_end      0xe06

/// Song 'g_ingame' array declaration
extern void g_ingame[g_ingame_size];
