///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: sound/menu.aks
/// Generation time: Fri 20 Nov 2020 05:00:11 PM CET
///

/// Song 'g_menu' metadata macros
#define g_menu_address  0x0E07
#define g_menu_size     362
#define g_menu_end      0xf70

/// Song 'g_menu' array declaration
extern void g_menu[g_menu_size];
