///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: sound/start.aks
/// Generation time: Fri 20 Nov 2020 05:00:13 PM CET
///

/// Song 'g_start' metadata macros
#define g_start_address  0x0200
#define g_start_size     300
#define g_start_end      0x32b

/// Song 'g_start' array declaration
extern void g_start[g_start_size];
